In [38]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
glass = pd.read_csv("Glass.csv")

In [9]:
le = LabelEncoder()
y = glass["Type"]
X= glass.drop("Type", axis = 1)

In [14]:
# create training and testing;

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 24, test_size =0.3, stratify = y)


In [46]:
gaussian = GaussianNB()

gaussian.fit(X_train,y_train)
y_pred = gaussian.predict(X_test)
y_pred_prob = gaussian.predict_proba(X_test)

# model evaluation;
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

print("the log_loss is: ",log_loss(y_test, y_pred_prob))

[[ 0  2  0  0  0 19]
 [ 2  2  1  0  0 18]
 [ 0  1  2  1  0  0]
 [ 0  0  0  8  0  1]
 [ 0  0  0  0  3  0]
 [ 0  1  0  0  0  4]]
                                      precision    recall  f1-score   support

    building_windows_float_processed       0.00      0.00      0.00        21
building_windows_non_float_processed       0.33      0.09      0.14        23
                          containers       0.67      0.50      0.57         4
                           headlamps       0.89      0.89      0.89         9
                           tableware       1.00      1.00      1.00         3
     vehicle_windows_float_processed       0.10      0.80      0.17         5

                            accuracy                           0.29        65
                           macro avg       0.50      0.55      0.46        65
                        weighted avg       0.34      0.29      0.27        65

0.2923076923076923
the log_loss is:  6.392423630618249


In [44]:
############# logistic regression #######################


In [52]:
lr = LogisticRegression()

lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
y_pred_prob =lr.predict_proba(X_test)

#### evalution model##########

print("accuracy_score: ",accuracy_score(y_pred,y_test))
print("the confusion matix: ",confusion_matrix(y_test,y_pred))
print("log loss is:", log_loss(y_test,y_pred_prob))


accuracy_score:  0.6461538461538462
the confusion matix:  [[17  4  0  0  0  0]
 [ 9 14  0  0  0  0]
 [ 0  1  2  1  0  0]
 [ 0  1  0  8  0  0]
 [ 0  0  0  2  1  0]
 [ 2  3  0  0  0  0]]
log loss is: 1.013442036861935


C:\Users\Rohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
